### ISSUE TITLE
[Feat] 1주차 세미나 과제

### ISSUE THREAD

**Issue by ahra1221** [GO-SOPT-iOS-Part/KoAhRa#1]
## Issue 🍏
1주차 세미나 과제

## Todo 🔍
- [x] 세미나 코드 복습
- [x] 새로운 UIComponent 활용 및 속성 추가하기
- [x] 금잔디조와 키워드 공부
