### ISSUE TITLE
[Feat] 4주차 세미나 과제

### ISSUE THREAD

**Issue by ahra1221** [GO-SOPT-iOS-Part/KoAhRa#15]
## Issue 🍏
4주차 세미나 과제

## Todo 🔍
- [x] 회원가입 서버통신 복습
- [x] open weather api 구현
- [x] TMDB API 붙이기 - 기본과제
