### ISSUE TITLE
[Feat] 2주차 세미나 과제

### ISSUE THREAD

**Issue by ahra1221** [GO-SOPT-iOS-Part/KoAhRa#3]
## Issue 🍏
2주차 세미나 과제

## Todo 🔍
- [x] 세미나 코드 복습
- [x] 세미나 실습 2개 코드 작성
- [ ] 금잔디조와 키워드 공부
