### ISSUE TITLE
[Feat] 2주차 TVING 클론코딩

### ISSUE THREAD

**Issue by ahra1221** [GO-SOPT-iOS-Part/KoAhRa#4]
## Issue 🍏
2주차 TVING 클론코딩 기본과제

## Todo 🔍
- [x] 기본과제
- 기능
    - [x] 아이디, 비밀번호 텍스트필드 각각 활성화되었을 때 border 컬러 수정
        - 비활성화일 때는 제일 기본
    - [x] 아이디, 비밀번호 텍스트필드의 텍스트가 !isEmpty일 때 버튼을 활성화
    - [x] 활성화 된 로그인하기 버튼을 클릭했을 때, 아래와 같이 아이디를 데이터 전달
    - [x] 비밀번호 텍스트필드 default 값은 security가 적용
    - [x] 눈 모양 버튼을 클릭 시, security를 해제
    - [x] 글 삭제 버튼을 클릭 시, 아이디, 비밀번호 텍스트필드를 각각 클리어
