### ISSUE TITLE
[Feat] 2주차 TVING 클론코딩 - 심화과제

### ISSUE THREAD

**Issue by ahra1221** [GO-SOPT-iOS-Part/KoAhRa#8]
## Issue 🍏
2주차 TVING 클론코딩 심화과제

## Todo 🔍
- [x] 심화과제
    - [x] 이메일 정규식 추가
    - [x] 바텀시트에서 저장한 닉네임을 세번째 뷰에서 아이디 대신 보여주기
    - [x] 데이터의 흐름이 BottomSheet → 로그인뷰 → 로그인 완료뷰 순서로
    - [x] 닉네임 텍스트필드가 입력이 되었을 때, 버튼 활성화
    - [x] 닉네임 텍스트필드의 텍스트는 한글로 제한하기
